spring:
  application:
    name: Bulk_data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/batchdemo1
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
   jdbc: 
     initialize-schema: ALWAYS 
